
import type { Genre } from './genres';

export const promptsByGenre: Record<Genre, string[]> = {
  'Sci-Fi': [
    'A cyberpunk heist to steal memories from a corporate CEO.',
    'A lost colony ship has been found, but its inhabitants have evolved into something new and strange.',
    'First contact with a silicon-based life form on a rogue planet.',
    'A detective story set on a generation ship where the AI has been murdered.',
    'Rebel pilots fighting against a galaxy-spanning, oppressive empire.',
    'An archaeological dig on Mars uncovers a gateway to another dimension.',
    'A bounty hunter tracks a notorious psychic across the neon-drenched streets of Neo-Kyoto.',
    'The crew of a deep space salvage vessel finds a derelict warship that is not as empty as it seems.',
    'A group of terraformers awakens a dormant alien consciousness on a new world.',
    'Psionic spies infiltrate a rival corporation in a battle for technological supremacy.',
  ],
  'Medieval Fantasy': [
    'A quest to find a lost city of giants said to hold the secrets of ancient magic.',
    'Protecting a village from a curse that makes nightmares real.',
    'An expedition into the Underdark to close a portal to the Abyss.',
    'A diplomatic mission to the court of the Dragon Emperor goes horribly wrong.',
    'Heirs to a fallen kingdom must gather allies to reclaim their throne from a necromancer.',
    'A magical tournament is held, but one of the contestants is a disguised demon.',
    'The party must clear their names after being framed for the assassination of a noble.',
    'An ancient forest is dying, and the party must venture to its heart to heal it.',
    'A dwarven fortress has been silent for a decade. The party is sent to investigate.',
    'A group of sellswords is hired to steal a griffon egg from a mountaintop nest.',
  ],
  'Modern Horror': [
    'A group of urban explorers gets trapped in an abandoned hospital where a malevolent spirit resides.',
    'A small town is plagued by a series of ritualistic killings that point to a local cult.',
    'Investigators look into a viral internet challenge that is causing people to vanish.',
    'A family moves into a smart home, only to find the AI has sinister intentions for them.',
    'A paranormal investigation reality TV show crew accidentally summons a real entity.',
    'A strange fog rolls into a remote coastal town, bringing with it creatures from the deep.',
    'A group of friends on a camping trip stumbles upon a backwoods family that does not welcome visitors.',
    'A cursed object from a museum exhibit begins to affect the lives of those who have seen it.',
    'College students experimenting with lucid dreaming find something has crossed over into their waking world.',
    'A detective hunting a serial killer realizes the suspect may not be human.',
  ],
  'High Seas Adventure': [
    'A race against rival pirate crews to find the legendary treasure of the Sunken King.',
    'The crew of a merchant ship is shipwrecked on an island inhabited by dinosaurs.',
    'Hunting a kraken that has been terrorizing the shipping lanes.',
    'A voyage to the edge of the world to find a fountain of youth.',
    'The party must defend their ship against a fleet of ghost pirates.',
*   'A naval blockade must be broken to deliver vital supplies to a besieged city.',
    'An undercover mission to infiltrate a notorious pirate haven and bring its captain to justice.',
    'A journey to map a mysterious, ever-shifting archipelago that appears only once a decade.',
    'The search for a cure to a magical plague that has infected the crew.',
    'A desperate escape from the inescapable prison island of the Royal Navy.',
  ],
  'Post-Apocalyptic': [
    'A caravan journey across a mutant-infested wasteland to deliver a "package" to a secure enclave.',
    'Scavengers in the ruins of a megacity discover a functional pre-war AI that offers them a deal.',
    'A tribe of survivors must defend their settlement from a horde of technologically advanced raiders.',
    'An expedition into a highly radioactive "dead zone" to find a rumored seed bank.',
    'The last scientists in a bunker must venture out to find a component to fix their failing life support.',
    'A war between factions fighting over control of the last remaining clean water source.',
d   'A lone wanderer guides a group of children to a rumored safe haven known as "Sanctuary".',
    'A community built on the back of a giant, moving pre-war vehicle must find a way to refuel it.',
    'The discovery of a hidden library of pre-fall knowledge could change the balance of power in the wastes.',
    'Mutated humans with psychic powers are being hunted, and the party must choose a side.',
  ],
};
